version: '3'

services:
    reverse_proxy:
        build: ./reverse_proxy
        restart: always
        networks:
          - reverse_proxy_network
        depends_on:
            - web
        ports:
          - "443:443"
          - "80:80"

    web:
        build: ./front_end
        restart: always
        networks:
            - reverse_proxy_network

    api:
        build: ./back_end
        restart: always
        depends_on:
            - db
        environment:
            - API_PORT
            - ROOT_ID
            - PIN_CODE
            - SECRET_KEY
            - MODE=prod
            - REDIS_HOST=redis
            - REDIS_PORT
            - DATABASE_NAME
            - DATABASE_PASSWORD
            - DATABASE_USER
            - DATABASE_PORT
            - DATABASE_HOST=db
            - DATABASE_URL=postgresql://$DATABASE_USER:$DATABASE_PASSWORD@db:$DATABASE_PORT/$DATABASE_NAME
        ports:
            - "${API_PORT}:${API_PORT}"
        networks:
            - backend

    redis:
        image: redis:alpine
        restart: always
        networks:
            - backend

    db:
        image: postgres:alpine
        restart: always
        depends_on:
            - redis
        environment: 
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        networks:
            - backend
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./back_end/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


networks:
    backend:
    reverse_proxy_network:

volumes:
    db-data:
